<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rogue</string>
	</array>
	<key>name</key>
	<string>Rogue</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\b(class|routine|augment)\b\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.rogue</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Class Declaration|Routine Definition|Class Augment</string>
			<key>end</key>
			<string>($)</string>
			<key>name</key>
			<string>meta.class.rogue</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scope_declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(method|routine|task)\b\s*</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.rogue</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Method|Routine|Task declaration</string>
			<key>end</key>
			<string>($)</string>
			<key>name</key>
			<string>meta.methodtype.rogue</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#method_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method_params</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#method_return</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(endClass|endRoutine|endAugment)\b</string>
			<key>name</key>
			<string>storage.type.rogue</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(function|endFunction)\b</string>
			<key>name</key>
			<string>storage.type.rogue</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(with|instance|endInstance)\b</string>
			<key>name</key>
			<string>storage.type.rogue</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(augment|endAugment|framework|endFramework)\b</string>
			<key>name</key>
			<string>storage.type.rogue</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(insertUnderlying|useFramework)\b</string>
			<key>name</key>
			<string>keyword.other.rogue</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(require|assert)\b</string>
			<key>name</key>
			<string>support.function.rogue</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(ensure)\b</string>
			<key>name</key>
			<string>support.function.rogue</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords_formatting</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords_control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords_loop</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords_other</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#language_variables</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scope_declaration</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\#\{)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.begin.rogue</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>comment.block.rogue</string>
					<key>end</key>
					<string>(\}\#)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>comment.block.end.rogue</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.comment.block.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>((#).*)</string>
					<key>name</key>
					<string>comment.line.number-sign.rogue</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\b|\-)[0-9]+\b</string>
					<key>name</key>
					<string>constant.numeric.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false|null|pi|infinity|NaN)\b</string>
					<key>name</key>
					<string>constant.language.rogue</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Bytes</string>
					<key>match</key>
					<string>(?:0x([0-9]|[A-F]){2})</string>
					<key>name</key>
					<string>constant.other.rogue</string>
				</dict>
			</array>
		</dict>
		<key>keywords_control</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(which|whichIs|case|caseNext|others|endWhich|endWhichIs|block|endBlock)\b</string>
					<key>name</key>
					<string>keyword.control.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(if|elseIf|else|endIf|contingent|endContingent|satisfied|unsatisfied|try|catch|endTry)\b</string>
					<key>name</key>
					<string>keyword.control.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(return|select|necessary|sufficient|noAction|yield|compileError)\b</string>
					<key>name</key>
					<string>keyword.control.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(try|catch|finally)\b</string>
					<key>name</key>
					<string>keyword.control.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(unitTest|endUnitTest)\b</string>
					<key>name</key>
					<string>keyword.control.rogue</string>
				</dict>
			</array>
		</dict>
		<key>keywords_formatting</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(ENUMERATE|DEFINITIONS|SETTINGS|CATEGORIES)\b</string>
					<key>name</key>
					<string>keyword.other.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(DEPENDENCIES|PROPERTIES|METHODS|ROUTINES)\b</string>
					<key>name</key>
					<string>keyword.other.rogue</string>
				</dict>
			</array>
		</dict>
		<key>keywords_loop</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(while|endWhile|forEach|endForEach|in|of|step|await|downTo)\b</string>
					<key>name</key>
					<string>keyword.loop.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(loop|endloop)\b</string>
					<key>name</key>
					<string>keyword.loop.rogue</string>
				</dict>
			</array>
		</dict>
		<key>keywords_other</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(escapeForEach|escapeWhile|escapeLoop|escapeTry)\b</string>
					<key>name</key>
					<string>keyword.other.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(escapeWhich|escapeWhichIs|escapeIf|escapeContingent|escapeBlock|nextIteration)\b</string>
					<key>name</key>
					<string>keyword.other.rogue</string>
				</dict>
			</array>
		</dict>
		<key>language_variables</key>
		<dict>
			<key>match</key>
			<string>\b(this|prior)\b</string>
			<key>name</key>
			<string>variable.language.rogue</string>
		</dict>
		<key>method_name</key>
		<dict>
			<key>match</key>
			<string>((\w+)((?=\()|(?=\-)|(?=\n)))</string>
			<key>name</key>
			<string>entity.name.function.rogue</string>
		</dict>
		<key>method_params</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>end</key>
			<string>(\))</string>
			<key>name</key>
			<string>meta.method.params.rogue</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;!:|=|\.|\$|-)\b\w+(?:(?=\=)|(?=:)|(?=,)|(?=\)))</string>
					<key>name</key>
					<string>variable.parameter.rogue</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#strings</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operators</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
			</array>
		</dict>
		<key>method_return</key>
		<dict>
			<key>begin</key>
			<string>(-&gt;)</string>
			<key>end</key>
			<string>($)</string>
			<key>name</key>
			<string>meta.method.return.rogue</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scope_declaration</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#types</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#language_variables</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(and|or|xor|not|instanceOf|is|isReference)\b</string>
					<key>name</key>
					<string>keyword.operator.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(=|==|!=|\+|(?&lt;!=\s)(?&lt;!=)-|\*|\/|\^|%|(?&lt;!&gt;)&gt;(?!&gt;)|&gt;=|(?&lt;!&lt;)&lt;(?!&lt;)|&lt;=)</string>
					<key>name</key>
					<string>keyword.operator.rogue</string>
				</dict>
			</array>
		</dict>
		<key>scope_declaration</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(overlaying|underlying)\b</string>
					<key>name</key>
					<string>storage.modifier.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(readOnly|writeOnly|public|private|const|local|singleton|primitive|aspect)\b</string>
					<key>name</key>
					<string>storage.modifier.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(native|inline|essential|abstract|final|compound|propagated|foreign|preferred)\b</string>
					<key>name</key>
					<string>storage.modifier.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(api|nonessential)\b</string>
					<key>name</key>
					<string>storage.modifier.rogue</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(")(?:(?=(\\?))\2.)*?\1</string>
					<key>name</key>
					<string>string.quoted.double.rogue</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(')(?:(?=(\\?))\2.)*?\1</string>
					<key>name</key>
					<string>string.quoted.single.rogue</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>match</key>
			<string>\b(Int64|Int32|Byte|Character|Real64|Real32|Logical|null|String)\b</string>
			<key>name</key>
			<string>storage.type.rogue</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.rogue</string>
	<key>uuid</key>
	<string>973adfa5-9430-470d-bbe6-7f8d2c07ca1c</string>
</dict>
</plist>
