BARD_SRC = \
  Alias.bard        \
  BCWriter.bard     \
  CmdQuery.bard     \
  Keywords.bard     \
  Parser.bard       \
  TargetRules.bard  \
  TokenReader.bard  \
  Analyzer.bard     \
  BardError.bard    \
  Cyber.bard        \
  Local.bard        \
  Preprocessor.bard \
  TaskVisitor.bard  \
  Type.bard         \
  Attributes.bard   \
  CPPWriter.bard    \
  CyberPlugin.bard  \
  Method.bard       \
  Property.bard     \
  Template.bard     \
  Types.bard        \
  Augment.bard      \
  Cmd.bard          \
  JSWriter.bard     \
  Op.bard           \
  Scanner.bard      \
  Token.bard        \
  Visitor.bard 

Cyber.bc: $(BARD_SRC)
	../../Programs/Mac/bard ../../Programs/BCC.bc --source-folders=../../Libraries/Bard Cyber.bard
